# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Superlinter Action

on:
  push:
    branches: ["nodejs_environment_job_greet"]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["10", "12"]
    steps:
      - name: Get Code
        uses: actions/checkout@v2
      - name: Superlinter Execution
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          VALIDATE_JAVASCRIPT_ES: true

      - name: Node Execution
        uses: "actions/setup-node@v2"
        with:
          node-version: ${{matrix.node}}
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Get Code
        uses: actions/checkout@v2
      - name: Jest execution
        run: npm install jest && npm test

  greet:
    runs-on: ubuntu-latest
    needs: ["lint", "test"]
    env:
      DESTINATION_PERSON: "2DAW"
    steps:
      - name: Greet User
        uses: adeloyedeji/github-actions-hello@v1.0
        with:
          who-to-greet: ${{env.DESTINATON_PERSON}}
